vim.cmd [[let g:gruvbox_material_foreground = "material"]]
vim.cmd [[let g:gruvbox_material_diagnostic_text_highlight = 1]]
vim.cmd [[let g:gruvbox_material_better_performance = 1]]
-- vim.cmd [[let g:gruvbox_material_diagnostic_virtual_text = 'colored']]
vim.cmd [[colorscheme gruvbox-material]]
